# Generated by Django 3.0.8 on 2020-07-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debtor', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptType',
            fields=[
                ('receipt_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('receipt_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('batch_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('check_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('check_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('receipt_notes', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('check_image_file_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('remittance_file_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Client')),
                ('debtor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='debtor.Debtor')),
                ('receipt_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.ReceiptType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
