# Generated by Django 3.0.8 on 2020-07-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDeliveryOption',
            fields=[
                ('invoice_delivery_option_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('option_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('option_description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceDeliveryTask',
            fields=[
                ('invoice_delivery_task_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('date_delivered', models.DateTimeField(blank=True, default=None, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
                ('invoice_delivery_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_delivery.InvoiceDeliveryOption')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
