# Generated by Django 3.0.8 on 2020-07-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionNote',
            fields=[
                ('collection_note_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('payment_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebtorResponse',
            fields=[
                ('debtor_response_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('debtor_response', models.CharField(max_length=50)),
                ('response_description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceCollectionNote',
            fields=[
                ('invoice_collection_note_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('collection_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.CollectionNote')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='collectionnote',
            name='debtor_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.DebtorResponse'),
        ),
    ]
