# Generated by Django 3.0.8 on 2020-07-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('contact_role_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('role_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('role_description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('debtor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('docket', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('dot_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('business_phone', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('business_fax', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('business_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('fax_noa', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fax_statement', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fax_invoice', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email_noa', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('email_invoice', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('email_statement', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('email_subject', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('originals_required', models.BooleanField(default=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_upload_website', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('invoice_upload_user', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('invoice_upload_password', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceDeliveryOption',
            fields=[
                ('option_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('option_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('option_description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('status_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('status_description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebtorNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('debtor_note', models.CharField(max_length=255)),
                ('is_alert', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('show_client', models.BooleanField(default=False)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_memo', to='debtor.Debtor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='debtor',
            name='invoice_delivery_option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debtor.InvoiceDeliveryOption'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debtor.Debtor'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debtor.Status'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address_1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address_2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cell_phone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('portal_access_login', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('portal_access_password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('contact_role', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debtor.ContactRole')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
