# Generated by Django 3.0.8 on 2020-07-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscChargeType',
            fields=[
                ('misc_charge_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('charge_name', models.CharField(max_length=50)),
                ('charge_description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverAdvance',
            fields=[
                ('over_advance_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('over_advance_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('date_closed', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_extended', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Client')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Terms')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverAdvanceNote',
            fields=[
                ('over_advance_note_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('note', models.CharField(max_length=255)),
                ('over_advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management.OverAdvance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiscCharge',
            fields=[
                ('misc_charge_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('note', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('misc_charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_management.MiscChargeType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
