# Generated by Django 3.0.8 on 2020-07-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debtor', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('invoice_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('load_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('bol_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('is_fuel_advance', models.BooleanField(default=False)),
                ('is_document_ready', models.BooleanField(default=False)),
                ('date_funded', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_due', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_on_hold', models.BooleanField(default=False)),
                ('is_charged_back', models.BooleanField(default=False)),
                ('job_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('load_lable', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('track_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('pickup_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pickup_city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pickup_state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pickup_zip', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('delivery_city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('delivery_state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('delivery_zip', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('memo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('document_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('document_file_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Client')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debtor.Debtor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('invoice_status_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('line_item_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('line_item_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('line_item_description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOption',
            fields=[
                ('purchase_option_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NOA',
            fields=[
                ('noa_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('is_customized', models.BooleanField(default=False)),
                ('is_debtor_notified', models.BooleanField(default=False)),
                ('debtor_notification_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtor.Debtor')),
                ('terms', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Terms')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItems',
            fields=[
                ('invoice_line_item_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Invoice')),
                ('line_item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.LineItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='noa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.NOA'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.PurchaseOption'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.InvoiceStatus'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Terms'),
        ),
    ]
